theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
auto-format = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
"$" = "goto_line_end"
"_" = "goto_line_start"

